/*

 SPRITES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 8 to 9

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char player[] =
{
  0x00,0x00,0x38,0x38,0x38,0x38,0x14,0x14,
  0x7C,0x7C,0x50,0x50,0x3C,0x3C,0x64,0x64,
  0x00,0x00,0x38,0x38,0x38,0x38,0x50,0x50,
  0x7C,0x7C,0x14,0x14,0x78,0x78,0x4C,0x4C
};

/* End of SPRITES.C */
